name: Angular Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: npm dependencies
      run: npm install     
    - name: Build
      run: npm run build -- --prod    
    - name: FTP To Server
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.myconcertpal.com
        FTP_USERNAME: ftpuser
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ./dist
        ARGS: set ssl:verify-certificate false; set ftp:ssl-force true